# GitHub Actions test for make_gitconfig and make_gitignore scripts;
# expects scripts to return 0 and make result files, fails otherwise.
#
# Latest revision: 2026-04-03
#
# Created and unlicensed by Mikołaj Bartnicki <mikolaj@bartnicki.org>;
# please read UNLICENSE file for details.

name: Check scripts

on:
  push:
  workflow_dispatch:
jobs:
  test-gitconfig:
    uses: mystikolaos/actions/.github/workflows/check-shell-command.yml@main
    with:
      packages: "git"
      command: "./make_gitconfig"
      make-executable: true
      expected-file: "~/.gitconfig"

  test-gitignore:
    uses: mystikolaos/actions/.github/workflows/check-shell-command.yml@main
    with:
      packages: "git"
      command: "./make_gitignore"
      make-executable: true
      expected-file: "~/.gitignore"
